refactor: Use static methods to compose the load method (#47)
* feat(Testability Enhancements): Add custom fontLoader param to static cache loader methods

- Add `fontLoader` parameter to `loadCachedFont`
- Add `fontLoader` parameter to `loadCachedFamily`
- Expose `fontLoader` only for testing

* refactor(`loadCachedFamily`): Add null check to font

- Before:
  * `NoSuchMethodError` was thrown.
  * In a try-catch block, the error thrown won't immediately stop the execution of the function.
- After: Assertion error with a clear error message is thrown

* refactor: Use static methods to compose the load method

- `DynamicCachedFonts.load` now returns FileInfo instead of File
- Use `loadCachedFamily` and `cacheFont` to compose the load method
- Implement font file validity checker to preserve `Cachemanager.getSingleFile`'s behaviour

* build(deps): Remove `file` package